### ISSUE TITLE
botがRTCにしたrequestがたまにTimeoutするようになる。

### ISSUE THREAD

**Issue by tasuren** [RT-Team/rt-backend#12]
一日程経過すると起きるバグ
何かしら起きている。
原因不明

**Comment by tuna2134** [comment]
そう言うもの
ボットがハートビート送ったら？

**Comment by tasuren** [comment]
ここでいうRTCはDiscordとの通信じゃないからね。

**Comment by tuna2134** [comment]
いや
わかっている
同じバグになったことがあるから、ハートビートを送れば直った

**Comment by tasuren** [comment]
もしかしてping?

**Comment by tuna2134** [comment]
まあ生存確認するやつかな

**Comment by tuna2134** [comment]
定期的に何か送信しとけばいい

**Comment by tasuren** [comment]
使われてない時は`Nothing`を送りまくってる。

**Comment by tasuren** [comment]
ping/pongをするようにして返信こなかったら再接続するようにしたら恐らく直った。
