### ISSUE TITLE
ダッシュボードのトークンに期限を設ける

### ISSUE THREAD

**Issue by tuna2134** [RT-Team/rt-backend#15]
期限を設けて一定の時間が経ったらログインをするよう促す

**Comment by tasuren** [comment]
なんで？

**Comment by tuna2134** [comment]
ブラウザ閉じたらクッキーがリセットされるから

**Comment by tasuren** [comment]
めんどくさいな

**Comment by tuna2134** [comment]
簡単だよ
response.cookies[“token”] = “”
response.cookies[“token”][“expires”] = datetime.datetime

**Comment by tuna2134** [comment]
詳しくは[これ](https://sanic.dev/en/guide/basics/cookies.html#writing)をみて

**Comment by tasuren** [comment]
君が言いたかったのはそういう事だったのか。  
ダッシュボードでログインし直してっていうアラートをしばらくしたら出すのかと思った。

**Comment by tasuren** [comment]
めんどくさいな

**Comment by tuna2134** [comment]
でも実際七日間でトークンリセットだから。。。

**Comment by tasuren** [comment]
あ、もしかしてOAuthのTOKENのこと言ってる？

**Comment by tuna2134** [comment]
うん

**Comment by tasuren** [comment]
RTのやつTOKENじゃなくてユーザーIDとなんかをクッキーに入れててTOKEN入れてないから大丈夫

**Comment by tuna2134** [comment]
なら定期的にやってほしい(更新とか)

**Comment by tasuren** [comment]
なんで更新？

**Comment by tuna2134** [comment]
アバターとか反映

**Comment by tasuren** [comment]
そういうのはユーザーIDからバックエンド(bot経由で)取得されて毎回新しいから大丈夫

**Comment by tuna2134** [comment]
でも設けることでブラウザの閉じる際のクッキー削除がされないはず

**Comment by tasuren** [comment]
うーん別にもういいかな、めんどくさいから。

**Comment by tuna2134** [comment]
ええ。。
やった方がいいのに

**Comment by minato37103710** [comment]
別にやらんくってええやろ

**Comment by tuna2134** [comment]
絶対いるよ

**Comment by minato37103710** [comment]
さにっくはブラウザ閉じたらCookie自動削除なん？

**Comment by tuna2134** [comment]
ちがう期限なしクッキー自動削除はブラウザの仕様

**Comment by minato37103710** [comment]
俺のサイトはされないのはなんでなん

**Comment by minato37103710** [comment]
別に期限とか決めてないで
