### ISSUE TITLE
GBANリストをjson形式で公開(API)

### ISSUE THREAD

**Issue by kazuma11121125** [RT-Team/rt-backend#17]
こっちであってるよね

**Comment by tasuren** [comment]
Yeah

**Comment by kazuma11121125** [comment]
他のBOTでもRTbotのGBANリストに入っているユーザーをBANできるようになるため、効果が上がると思うから。
というか、音夢さんか誰かが言ってた記憶。
jsonの中身は、IDとBANした理由があればいいかな。

**Comment by tuna2134** [comment]
でもそうするならcloudflareの設定緩めないと

**Comment by tasuren** [comment]
めんどくさいな。
