### ISSUE TITLE
bump機能関連の提案

### ISSUE THREAD

**Issue by yaakiyu** [RT-Team/rt-backend#64]
・bumpのお知らせ時の文源に「!d bump」って打ってあげてね！とかの、Discord詳しくない方向けの一言がほしいです！
by melty#5493

僕から・bump通知設定したときにいついつに通知するよ～っていう具体的な数字が欲しい。あとbump関連はEmbedがいいな。

**Comment by tasuren** [comment]
![image](https://user-images.githubusercontent.com/45121209/134770589-605febb6-65fb-4cbe-befb-e18a4e7f0b25.png)
実装した。Discordのタイムスタンプのやつ便利。
