### ISSUE TITLE
permコマンドめちゃくちゃ見にくい

### ISSUE THREAD

**Issue by yaakiyu** [RT-Team/rt-backend#65]
permコマンドの外見がかなりわるくなりましたね((
やっぱり名無し。氏のころのあれがとってもみやすい...()

**Comment by yaakiyu** [comment]
あとpermの引数に`everyone`指定出来てほしい。メンションはありでも無しでも

**Comment by tasuren** [comment]
> あとpermの引数に`everyone`指定出来てほしい。メンションはありでも無しでも

できるようにして絵文字で表示するようにした。
