### ISSUE TITLE
ログ機能

### ISSUE THREAD

**Issue by tuna2134** [RT-Team/rt-backend#85]
ログを表示する機能

**Comment by tasuren** [comment]
> ログを表示する機能

実は存在はするがヘルプに書くのを忘れていた。
了解

なんなら`cogs.translator`のヘルプ追加を見習ってPRもだせるよ。

**Comment by tuna2134** [comment]
Ok
これからそうする

**Comment by tuna2134** [comment]
もう追加したから閉じとく
